[[services]]
name = "pingDaemon"
path = "api"
dockerfile = "Dockerfile.api"
port = 8000
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
startCommand = "/start-api.sh"

[[services]]
name = "pingdaemon-worker"
path = "worker"
dockerfile = "Dockerfile.worker"
restartPolicyType = "ON_FAILURE"
startCommand = "celery -A app.celery_worker worker --loglevel=info --concurrency=2"