services = [
  {
    name = "pingDaemon",
    path = ".",
    dockerfile = "Dockerfile.api", 
    startCommand = "./start-api.sh",
    port = "$PORT",
    healthcheckPath = "/health",
    restartPolicyType = "ON_FAILURE"
  },
  {
    name = "pingdaemon-worker",
    path = ".",
    dockerfile = "Dockerfile.worker",
    restartPolicyType = "ON_FAILURE"
  }
]