[[services]]
name = "pingdaemon-api"
dockerfile = "Dockerfile.api"

[services.healthcheck]
path = "/health"

[services.variables]
SERVICE_TYPE = "api"

[[services]]
name = "pingdaemon-worker"
dockerfile = "Dockerfile.worker"

[services.variables]
SERVICE_TYPE = "worker"