services = [
  {
    name            = "pingDaemon"
    path            = "api"                      # <---- CHANGE this
    dockerfile      = "Dockerfile.api"           # fine if it stays .api
    startCommand    = "./start-api.sh"
    port            = 8080
    healthcheckPath = "/health"
    restartPolicyType = "ON_FAILURE"
  },
  {
    name            = "pingdaemon-worker"
    path            = "worker"                   # <---- CHANGE this
    dockerfile      = "Dockerfile.worker"        # fine if it stays .worker
    restartPolicyType = "ON_FAILURE"
  }
]
