services = [
  {
    name = "pingDaemon",
    path = "api",
    dockerfile = "Dockerfile.api",
    startCommand = "./start-api.sh",
    port = 8080,
    healthcheckPath = "/health",
    restartPolicyType = "ON_FAILURE"
  },
  {
    name = "pingdaemon-worker",
    path = "worker",
    dockerfile = "Dockerfile.worker",
    startCommand = "celery -A app.celery_worker worker --loglevel=info --concurrency=2",
    restartPolicyType = "ON_FAILURE"
  }
]
