services = [
  {
    name = "pingDaemon",
    path = ".",
    dockerfile = "Dockerfile.api", 
    startCommand = "./start-api.sh",
    port = "$PORT",  # Only this line changed
    healthcheckPath = "/health",
    restartPolicyType = "ON_FAILURE"
  },
  {
    name = "pingdaemon-worker",
    path = ".",
    dockerfile = "Dockerfile.worker",
    startCommand = "celery -A app.celery_worker worker --loglevel=info --concurrency=2 --max-tasks-per-child=100 --time-limit=300 --soft-time-limit=240",
    restartPolicyType = "ON_FAILURE"
  }
]